# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Check out calc tests
        run: python test.py
      
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: compile to bytecode
        run: python -m py_compile hello.py > hello.pyc
      - name: setup compiler
        run: pip install pyinstaller
      - name: compile to package
        run: pyinstaller hello.py  --noconfirm --onefile --console
      - name: setup git config
        run: |
          git config user.name "TurnTheSlayerXD"
          git config user.email "slayer2004@list.ru" 
      # commit files
      - name: Commit files
        run: |
            git add hello.cpython-311.pyc
            git add test.py
            git add hello.py
            git add dist/
            git add build/hello/hello.pkg
            git commit -a -m "Push finished"
            git push --force origin master
            git pull --rebase
            git push origin master

      
